sudo: required

services:
  - docker
  
script:
  - docker build --tag coil/hello_world_travis_ci .
  - docker run coil/hello_world_travis_ci
  
before_deploy:
  - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}
  
deploy:
  provider: script
  script: docker push coil/hello_world_travis_ci
  on:
    branch: master
